name: Branch Filter Workflow

on:
  push:
    branches:
      - main  # Only trigger on pushes to main branch

jobs:
  test-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current branch
        run: echo "Running on branch: ${{ github.ref }}"
