name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
      - feature-branch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run PR test
        run: echo "Running test on PR from feature branch"

      - name: Print deploy
        run: echo 'deploy'
